apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - migration-job.yaml
  - statistics-migration-job.yaml
  - deployment.yaml
  - place-sync-worker.yaml
  - statistics-worker.yaml
  - service.yaml
  - ingress.yaml
  - db-readonly-access.yaml
