apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: momo-workers
  labels:
    release: monitoring
spec:
  selector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          - momo-place-sync-worker
          - momo-statistics-worker
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
