apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: momo-api
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: momo-api
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
