---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: momo-api-env
  namespace: dnd-15th-3-dev
spec:
  encryptedData:
    GOOGLE_PLACES_API_KEY: AgCxZmyMQWxixuw3a7jx4wXKS6DJEbaqftaCtlOzgdEOoV8B2lMOTmx+NuKUokCuU7tPW+sS4BUWr6BwPk1c8CT10IGLmJ/fVTeCE1bL8hn18pnYIQPxEwmuzeao9aqfaP+aFufdpYFRYHDh2+aMP3Co+wAg4UD/PjYlIyya9dW836cJmgOrw8INYn7zqM4EIqaiwNfv8VOoIj9LlO+rG6Fdnaiba5c3eRd9idL+clvqS6j7w75N9ECOikrju0DTLaXOz4ROWpBuoO3lOx0C4VnV1kYpJHXhj1MeDtjewuk1vAsPaBAGKqDiJ5Ut30RUrVazlB4zw4gvrB5gyhnCikWd9KKliAps6DgZf4v1fVg+5lB61h8vBjegxv8mOEjVYd4f2VuhkqJZSgRZVaf8xv2bEIXCeUxJuKWYBp4rRYaDv/AmQ8afyVNfXR0MaPGkGWhsV21XTkiQ05lJlJnJqjK6C/MiZjiUajgsw3/FHh5O4IyV0yB6tfcC3b5H2LmNj8RL2502NgVMWx1d4KNFlN3NEcH8C860ApSqtmCP+7BYi8y6BEtE3SHCtHYH9T5Z4bQ5iqg8KaeSSII+9j7QJHUHHPg2wr4PFXbG1HGfsg09qq/F/njXWsqKPa/DCKF50J+tun1he89B98ZwOtcjo4KCd7ehP/kXPR/C7T/yzG3CwP1XRQUNoRjExX5y8b+G9FmtnwxGRJghyJCTm6HftqcpsxzEiFDzZst0JAecKlqfxZ/5KsR4LJM=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/patch: "true"
      name: momo-api-env
      namespace: dnd-15th-3-dev
