---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: momo-api-env
  namespace: dnd-15th-3-dev
spec:
  encryptedData:
    GOOGLE_PLACES_API_KEY: AgCOS0mLr+mRXMM0rM61iXMf7qjJK9ltANGe3J5jIIykMN405rwG/hUBy2uvLUbS47AVKgYd17+SzpjvfuNsrgfamv08gNZBlNdfSbxCCbJMRyBgP2VA3i4Q+Q7RqFyW7B1JQXJseX11tDAnM5oE5uVgVUcOAp42yAc3HZzQeMuzCof5tIbZSkLS4fsl4pIJOzwof0EBEndiKwUQXo7JSxqwMY/B5fwXPWgPvfw1FMGdJfs2iJXG4MkcINbjWuw/wNL4iTTxzhnU9FR8AvkcPSdq94CHsGSNAP1UCfJRrXn9s+TF4Rw6QYNwc6n8Nq5m/xRu0PuZB0t5qdF4jTNPeFn1odHKYyRwnSawVOFIRUSDOaJwaI1kSjp1SdlGkUEp7Had9DswIWcYTm6kpEo36selwnf1rRSNXYZHYfSnBLZJheirDysX29ahenfaTEvip395MMxpbIT++B5DLb1StfGpZDBqWIzSPqrv/d2E3C9Hxv19Y6QU1h4WSODVctrH8ym4cdcGWxRf50Qy5oUhpZO2jasw2Qy+12hl0zllo1hPgP9DsIzo26oH/nPHW0TzI30HTB1sm/d9k00x5oC4RK4Juu5kBF83Sm1wWd2ygus2DTAvXFPmvCIX5ozeo0v26xxdDnvPPImLOiMnMe7TT9P4UnxPJ3p0W0xqspOAQAO7eEC0v5PrPkfBWc96tMZayaQ=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/patch: "true"
      name: momo-api-env
      namespace: dnd-15th-3-dev
