apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-developer
---
apiVersion: v1
kind: Secret
metadata:
  name: db-developer-token
  annotations:
    kubernetes.io/service-account.name: db-developer
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: db-developer
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["momo-postgres-auth", "momo-statistics-postgres-auth"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/portforward"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: db-developer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: db-developer
subjects:
  - kind: ServiceAccount
    name: db-developer
