apiVersion: apps/v1
kind: Deployment
metadata:
  name: momo-api
spec:
  template:
    spec:
      containers:
        - name: api
          env:
            - name: NODE_ENV
              value: development
            - name: CORS_ORIGINS
              value: "http://localhost:5173,http://localhost:6006,https://dnd-15th-3-frontend.pages.dev,https://*.dnd-15th-3-frontend.pages.dev"
            - name: DB_HOST
              value: momo-postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: momo-postgres-auth
                  key: POSTGRES_DB
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: momo-postgres-auth
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: momo-postgres-auth
                  key: POSTGRES_PASSWORD
            - name: DB_SSL
              value: "false"
