---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: momo-api-env
  namespace: dnd-15th-3-prod
spec:
  encryptedData:
    GOOGLE_PLACES_API_KEY: AgDG+eSoH4qSxKXmPdmKWXoSPEPMzLe3/aOL09RswWvNCVKKkt9bw31LRqNOKVXXVXUyetG0iTL30M2EOg6BxHhkmN+2cqFx9bb3RuS1srX5FlQuIC5Jbgfx6rSb6NTmpV3XIOVCszV91krZe4Innka9vbFjKaJo8FYP6Uo6B6qYXG4lCICqZKglXBuLZxOOA++9ajd5ktUX0SzJyohc2S2B6uiMaoh6LWccEZDbaFhRgl4Jvuw2wa2ZjsRzcmEdITQTpuUPfwY7FTCVgSi7hoDD4cPOCkovD3mgCK4zLE3ViZ8vOQUZpNKUhv1gZOjC851BlExU6pHrdTqaY+jjHN0WGdj7fC5ZZ779Qi1mbvGhk5LLdKceAysAqSpBfrJpeJFu347AJ4tPjNtwHUYUppAruAaXEW4ylXsASnH8hCE6cDG33ztI8pMgdK+4NUsIlIKPZ7WhZGtwcFNG/IWDvkZFI+LQdJms+707spRFybEQQobuR28Mvj6puhy1/4yILtRegxlP3puMzgAxXs9KzKSrX8IBKUZm8mHkRbSNlgnXeTd9I5tOXB+7M4w5xirIQ6nPqWeeuDZLKXfTnThvu2oN4cWhEpujEA7RxKdOQxNRE0C7XzR8S/ziZjN3IK1tH3ZKkDax+NMR3Ej0CLCibWGhQI4nKqPEwjsOarxkE2wWu0SCIC2E/jFtT437KdlJgu0=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/patch: "true"
      name: momo-api-env
      namespace: dnd-15th-3-prod
