---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: momo-api-env
  namespace: dnd-15th-3-prod
spec:
  encryptedData:
    GOOGLE_PLACES_API_KEY: AgDQ3VDvXmpMajBdIINn77Jd4fn3tmiZsJHgoUmHb1Sd395NOGkNSv2YXumgXHESfHQRQ6nRCpnd78Wr4gVd3TEyZLEAag5HM1FaD/umxhjgDkj6v5n94d+ezf2HSfyZL/0Rh4MAET8R47Jo2x82ZngL9kNfhzRymUL/aXWxFP3y9IEKhf56eUN34CaukM2hnzUtkrSRJyNuLDOY0G0X2msZ7TBK1H38AI+RDXkQLssC/VI8Jg2ic9oglnsFcMiuWZAdpcX02sTbtL8sN5pUC26cW8AVXVV0+YksHWkaHk5XF9kH2NCI2xBjufO7J11BFGrP9YQiGQ9HAw97+DmCTnyUWr8/1DfbnIH/16pzX92NzHFKV5LKmKqxv/NRIEx+HnB+IdiKwir9b/xYbfNBHoHyhb0bWxnxfOvVGbvilVxbuE9Tkwzqn8qA3DPTd5BfbeROzs6R8BI3ffIOtnxWfg5/jLW10dyNH1SNie3xF9fyLOMLLNbGKvyRa1XILe0nGTPsB59HYeBGFdwTheH/z8hTElbbhtarWoFkPKyMvltJ3fEFVcZeLI+MOSmDr1PKtQ0XB09rsmXQe6p7uwSybCwWlwejDKnqNlkaujDBL7oc4qbLztuj2QbIS/rxwSNRS8MoS133Orkc9IepDG/SxcXWLmJEUsI+Mb2ic7fCG7d0nNrBryIHqODAVAxRJ9Tj3BsWYX3ErmS1tiiDMYRnoHCUbsSBPCe4Uo/mlu8gMG11pTUXKr23rOc=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/patch: "true"
      name: momo-api-env
      namespace: dnd-15th-3-prod
