apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dnd-15th-3
resources:
  - ../../base
images:
  - name: ghcr.io/dnd-side-project/dnd-15th-3-backend
    newTag: main-adb5db01b39d5238dd6b3e13dd038c4ff11c14b8
patches:
  - path: ingress.yaml
  - path: environment.yaml
  - path: resources.yaml
