apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dnd-15th-3
resources:
  - ../../base
images:
  - name: ghcr.io/dnd-side-project/dnd-15th-3-backend
    newTag: main-bootstrap
patches:
  - path: ingress.yaml
  - path: resources.yaml
