apiVersion: v1
kind: Service
metadata:
  name: momo-statistics-postgres
  labels:
    app.kubernetes.io/name: momo-statistics-postgres
    app.kubernetes.io/component: statistics-database
    app.kubernetes.io/part-of: momo
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: momo-statistics-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres

