apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - application-develop.yaml
  - application-main.yaml
  - application-postgres-develop.yaml
  - application-postgres-main.yaml
  - image-updater.yaml
