apiVersion: batch/v1
kind: CronJob
metadata:
  name: momo-postgres-backup
spec:
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: backup
              emptyDir:
                sizeLimit: 6Gi
