apiVersion: batch/v1
kind: CronJob
metadata:
  name: momo-postgres-backup
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: upload
              env:
                - name: BACKUP_ENV
                  value: dev
